---
- name: install tomcat
  yum:
    name: tomcat
    state: latest

- name: create ansible tomcat directory
  file:
    path: "{{ webroot }}"
    state: directory

- name: copy static index.html to tomcat webapps/ansible/index.html
  template:
    src: index.html.j2
    dest: "{{ webroot }}/index.html"
    mode: 0644

- name: start tomcat and enable at boot
  service:
    name: tomcat
    state: started
    enabled: yes
